**ให้นิสิต เลือกเมนู File-->Save a copy in drive เพื่อคัดลอกไฟล์ไปไว้ในไดร์ฟของนิสิตก่อน และเปลี่ยนชื่อไฟล์เป็น รหัสนิสิต_week1.ipynb ก่อนส่งงานค่ะ**

1.จงสร้างเมทริกซ์     
\begin{equation*}
A =
\begin{bmatrix}
0 & -3  \\
-3 & 0
\end{bmatrix},
B =
\begin{bmatrix}
0 & 5  \\
-5 & 0
\end{bmatrix},
C =
\begin{bmatrix}
1 & -2  \\
2 & 1
\end{bmatrix}
\end{equation*}

 โดยใช้ Python

1.1	จงหา 2A + B

1.2 จงหา C - 3B

1.3     จงตรวจสอบว่า A$^T$B$^T$ = (AB)$^T$ หรือไม่
          ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No

1.4	จงตรวจสอบว่า  2A+2B = 4(B+A)  หรือไม่
          ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No

1.5	จงตรวจสอบว่า A เป็นเมทริกซ์สมมาตรหรือไม่
          ถ้าเป็นให้แสดงข้อความ Yes ไม่เป็นแสดงข้อความ No

1.6	จงตรวจสอบว่า B เป็นเมทริกซ์เสมือนสมมาตรหรือไม่
          ถ้าเป็นให้แสดงข้อความ Yes ไม่เป็นแสดงข้อความ No

1.7	จงตรวจสอบว่า C เป็นเมทริกซ์เสมือนสมมาตรหรือไม่
          ถ้าเป็นให้แสดงข้อความ Yes ไม่เป็นแสดงข้อความ No

1.8 จงหา C$^3$

1.9	จงตรวจสอบว่า (3A$^T$)C = 3(A$^T$C) หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ถ้าไม่เท่าแสดงข้อความ NO

2.จงสร้างเมทริกซ์     
\begin{equation*}
D =
\begin{bmatrix}
1 & 0 & 4 \\
2 & 6 & -1  
\end{bmatrix},
E =
\begin{bmatrix}
5 & 8  \\
0 & -2  \\
1 & 4
\end{bmatrix}
\end{equation*}   โดยใช้ Python


2.1 จงตรวจสอบว่า DE = ED หรือไม่
           ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No

2.2 จงตรวจสอบว่า (ED)$^T$ = D$^T$E$^T$ หรือไม่
          ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No









In [ ]:
#ชื่อ........................รหัส............

In [ ]:
import numpy as np

In [ ]:
matrix_A = np.array([[0,-3],[-3,0]])
matrix_B = np.array([[0,5],[-5,0]])
matrix_C = np.array([[1,-2],[2,1]])

In [ ]:
#1.1 จงหา 2A + B
print(2*(matrix_A) +matrix_B)

[[  0  -1]
 [-11   0]]


In [ ]:
#1.2 จงหา C - 3B
print(matrix_C - 3*matrix_B)

[[  1 -17]
 [ 17   1]]


In [ ]:
#1.3 จงตรวจสอบว่า A T B T  = (AB) T  หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No
print("a tranpose")
print(matrix_A.T)
print("b tranpose")
print(matrix_B.T)
print("_____________________")
print("A^T B^T")
print(matrix_A.T @ matrix_B.T)
print("_____________________")
print("(AB)^T")
print((matrix_A @ matrix_B).T)
print("_____________________")
# print(matrix_A.T @ matrix_B.T == (matrix_A @ matrix_B).T)
print("Answer:")
if np.array_equal(matrix_A.T @ matrix_B.T, (matrix_A @ matrix_B).T):
  print("Yes")
else:
  print("No")

a tranpose
[[ 0 -3]
 [-3  0]]
b tranpose
[[ 0 -5]
 [ 5  0]]
_____________________
A^T B^T
[[-15   0]
 [  0  15]]
_____________________
(AB)^T
[[ 15   0]
 [  0 -15]]
_____________________
Answer:
No


In [ ]:
#1.4 จงตรวจสอบว่า 2A+2B = 4(B+A) หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No
print(2*matrix_A + 2*matrix_B)
print("______________________")
print(4*(matrix_B + matrix_A))
print("______________________")
print(2*matrix_A + 2*matrix_B == 4*(matrix_B + matrix_A))
if np.array_equal(2*matrix_A + 2*matrix_B, 4*(matrix_B + matrix_A)):
  print("Yes")
else:
  print("No")

[[  0   4]
 [-16   0]]
______________________
[[  0   8]
 [-32   0]]
______________________
[[ True False]
 [False  True]]
No


In [ ]:
#1.5 จงตรวจสอบว่า A เป็นเมทริกซ์สมมาตรหรือไม่ ถ้าเป็นให้แสดงข้อความ Yes ไม่เป็นแสดงข้อความ No
def is_symmetric(matrix):
  return np.array_equal(matrix, matrix.T)
if is_symmetric(matrix_A):
  print("Yes")
else:
  print("No")

Yes


In [ ]:
#1.6 จงตรวจสอบว่า B เป็นเมทริกซ์เสมือนสมมาตรหรือไม่ ถ้าเป็นให้แสดงข้อความ Yes ไม่เป็นแสดงข้อความ No
if np.array_equal(-matrix_B,matrix_B.T):
  print("Yes")
else:
  print("No")

Yes


In [ ]:
#1.7 จงตรวจสอบว่า C เป็นเมทริกซ์เสมือนสมมาตรหรือไม่ ถ้าเป็นให้แสดงข้อความ Yes ไม่เป็นแสดงข้อความ No
if np.array_equal(-matrix_C,matrix_C.T):
  print("Yes")
else:
  print("No")

No


In [ ]:
#1.8 C**3
print(matrix_C**3)

[[ 1 -8]
 [ 8  1]]


In [ ]:
#1.9 จงตรวจสอบว่า (3A T )C = 3(A T C) หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ถ้าไม่เท่าแสดงข้อความ NO
print((3*matrix_A.T) @ matrix_C)
print("_____________________")
print(3*(matrix_A.T @ matrix_C))
print("_____________________")
if np.array_equal((3*matrix_A.T) @ matrix_C, 3*(matrix_A.T @ matrix_C)):
  print("Yes")
else:
  print("No")

[[-18  -9]
 [ -9  18]]
_____________________
[[-18  -9]
 [ -9  18]]
Yes


In [ ]:
#2.
matrix_D = np.array([[1,0,4],[2,6,-1]])
matrix_E = np.array([[5,8],[0,-2],[1,4]])

In [ ]:
#2.1 จงตรวจสอบว่า DE = ED หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No
print(matrix_D @ matrix_E)
print("_____________________")
print(matrix_E @ matrix_D)
print("_____________________")
print("Answer:")
if np.array_equal(matrix_D @ matrix_E, matrix_E @ matrix_D):
  print("Yes")
else:
  print("No")

[[ 9 24]
 [ 9  0]]
_____________________
[[ 21  48  12]
 [ -4 -12   2]
 [  9  24   0]]
_____________________
No


In [ ]:
#2.2 จงตรวจสอบว่า (ED) T  = D T E T  หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No
print(matrix_D.T @ matrix_E.T)
print("_____________________")
print((matrix_E @ matrix_D).T)
print("_____________________")
print("Answer:")
if np.array_equal(matrix_D.T @ matrix_E.T, (matrix_E @ matrix_D).T):
  print("Yes")
else:
  print("No")

[[ 21  -4   9]
 [ 48 -12  24]
 [ 12   2   0]]
_____________________
[[ 21  -4   9]
 [ 48 -12  24]
 [ 12   2   0]]
_____________________
Answer:
Yes
