<a href="https://colab.research.google.com/github/chanyut12/mathforcom/blob/main/66160195_21066_G2_w3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**การนับแถวเริ่มนับแถวที่ 0, 1, 2,...**
**การนับคอลัมน์เริ่มนับคอลัมน์ที่ 0, 1, 2,...**

**ให้นิสิต เลือกเมนู File-->Save a copy in drive เพื่อคัดลอกไฟล์ไปไว้ในไดร์ฟของนิสิตก่อน และเปลี่ยนชื่อไฟล์เป็น รหัสนิสิต_week3.ipynb ก่อนส่งงานค่ะ**

1. จงสร้างเมทริกซ์     
A =
\begin{bmatrix}
2 & -2 & 0   \\
1 & 4 & -5   \\
0 & 2 & 3   \\
\end{bmatrix}

โดยใช้ Python

1.1 จงตรวจสอบว่าเมทริกซ์ A เป็นเมทริกซ์เอกฐาน หรือไม่ ถ้าเป็นแสดงข้อความ Singular matrix.

1.2 จงแปลงเมทริกซ์ A ให้เป็นเมทริกซ์เอ๊กซลอน (Echelon form matrix) โดยการดำเนินการตามแนวแถว (Elementary row oparation)



1.3 จงหาเมทริกซ์ผกผัน (Inverse matrix) ของเมทริกซ์ A

1.4 จงตรวจสอบเมทริกซ์ผลลัพธ์ที่ได้จากข้อ 1.3 ว่าถูกต้องหรือไม่ หากถูกต้องแสดงข้อความว่า Correct หากไม่ถูกต้องแสดงข้อความ Incorrect โดยหากไม่ถูกต้องจงแก้ไขให้ถูกต้องด้วย

2.จงสร้างเมทริกซ์     
A =
\begin{bmatrix}
1 & 2 & 1  \\
2 & -4 & 5  \\
2 & 4 & 2
\end{bmatrix}
โดยใช้ Python

2.1	จงหา det(A)

2.2 จงหา Rank ของเมทริกซ์ที่กำหนดโดยใช้วิธีหาเมทริกซ์เอ็ซลอนลดรูปแบบแถว


In [ ]:
#ชื่อ..............................รหัส................

In [2]:
a = [[2,-2,0],[1,4,-5],[0,2,3]]

In [3]:
#1.1 จงตรวจสอบว่าเมทริกซ์ A เป็นเมทริกซ์เอกฐาน หรือไม่ ถ้าเป็นแสดงข้อความ Singular matrix.
import numpy as np
if(np.linalg.det(a) == 0): # if  det = 0 cant find inverse
  print("Singular matrix")
else:
  print("Non Singular matrix")

Non Singular matrix


In [22]:
#1.2 จงแปลงเมทริกซ์ A ให้เป็นเมทริกซ์เอ๊กซลอน (Echelon form matrix) โดยการดำเนินการตามแนวแถว (Elementary row oparation)
import numpy as np
a = np.array([[2,-2,0],[1,4,-5],[0,2,3]])
print('Matrix a:')
print(a)
n= a.shape[0]

def switch_rows(A,i,j):
  A[[i, j]] = A[[j, i]]
  return A

def scale_row(A,k,i):
  A[i] = k * A[i]
  return A

def add_row(A,k,i,j):
  A[i] += k * A[j]
  return A

a1 = scale_row(a,1/2,0) #R1/2
print('#1 Matrix a:')
print(a1)
a2 = add_row(a1,-1,1,0) #R2-R1
print('#2 Matrix A:')
print(a2)
a3 = scale_row(a2,(1/5),1) #R2/(1/5)
print('#3 Matrix a:')
print(a3)
a4 = add_row(a3,-2,2,1) #R3-R2
print('#4 Matrix A:')
print(a4)
a5 = scale_row(a4,(1/5),2) #R3-R1
print('#5 Echelon Matrix A:')
print(a5)

Matrix a:
[[ 2 -2  0]
 [ 1  4 -5]
 [ 0  2  3]]
#1 Matrix a:
[[ 1 -1  0]
 [ 1  4 -5]
 [ 0  2  3]]
#2 Matrix A:
[[ 1 -1  0]
 [ 0  5 -5]
 [ 0  2  3]]
#3 Matrix a:
[[ 1 -1  0]
 [ 0  1 -1]
 [ 0  2  3]]
#4 Matrix A:
[[ 1 -1  0]
 [ 0  1 -1]
 [ 0  0  5]]
#5 Echelon Matrix A:
[[ 1 -1  0]
 [ 0  1 -1]
 [ 0  0  1]]


In [23]:
#1.3 จงหาเมทริกซ์ผกผัน (Inverse matrix) ของเมทริกซ์ A (_____________________testtttttttttttttttttttttttttt_______________________)
inverse_of_a = np.around(np.linalg.inv(a), decimals = 2)
print(inverse_of_a)

[[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]


In [37]:
#1.3 จงหาเมทริกซ์ผกผัน (Inverse matrix) ของเมทริกซ์ A (__________________________________real__________________________________)
import numpy as np
a = np.array([[2,-2,0],[1,4,-5],[0,2,3]])
print('Matrix a:')
print(a)
n= a.shape[0]
aI = np.hstack([a,np.identity(n)])

def switch_rows(A,i,j):
  A[[i, j]] = A[[j, i]]
  return A

def scale_row(A,k,i):
  A[i] = k * A[i]
  return A

def add_row(A,k,i,j):
  A[i] += k * A[j]
  return A

a1 = scale_row(aI,1/2,0) #R1/2
print('#1 Matrix a:')
print(a1)
a2 = add_row(a1,-1,1,0) #R2-R1
print('#2 Matrix A:')
print(a2)
a3 = scale_row(a2,(1/5),1) #R2/(1/5)
print('#3 Matrix a:')
print(a3)
a4 = add_row(a3,-2,2,1) #R3-R2
print('#4 Matrix A:')
print(a4)
a5 = scale_row(a4,(1/5),2) #R3/(1/5)
print('#5 Matrix A:')
print(a5)
a6 = add_row(a5,1,1,2) # R2+R3
print('#6 Matrix A:')
print(a6)
a7 = add_row(a6,1,0,1) # R1+R2
print('#7 Matrix A:')
print(a7)

ainv = a7[:,n:] # inverse matrix
print('Matrix a inverse:')
print(ainv)

print('Matrix A @ Matrix A inverse')
print(a@ainv)

# print(np.around(a@ainv,decimals=0))
# if np.array_equal(np.around(a@ainv,decimals=0),np.identity(n)):
#   print("Correct")
# else:
#   print("Incorrect")

Matrix a:
[[ 2 -2  0]
 [ 1  4 -5]
 [ 0  2  3]]
#1 Matrix a:
[[ 1.  -1.   0.   0.5  0.   0. ]
 [ 1.   4.  -5.   0.   1.   0. ]
 [ 0.   2.   3.   0.   0.   1. ]]
#2 Matrix A:
[[ 1.  -1.   0.   0.5  0.   0. ]
 [ 0.   5.  -5.  -0.5  1.   0. ]
 [ 0.   2.   3.   0.   0.   1. ]]
#3 Matrix a:
[[ 1.  -1.   0.   0.5  0.   0. ]
 [ 0.   1.  -1.  -0.1  0.2  0. ]
 [ 0.   2.   3.   0.   0.   1. ]]
#4 Matrix A:
[[ 1.  -1.   0.   0.5  0.   0. ]
 [ 0.   1.  -1.  -0.1  0.2  0. ]
 [ 0.   0.   5.   0.2 -0.4  1. ]]
#5 Matrix A:
[[ 1.   -1.    0.    0.5   0.    0.  ]
 [ 0.    1.   -1.   -0.1   0.2   0.  ]
 [ 0.    0.    1.    0.04 -0.08  0.2 ]]
#6 Matrix A:
[[ 1.   -1.    0.    0.5   0.    0.  ]
 [ 0.    1.    0.   -0.06  0.12  0.2 ]
 [ 0.    0.    1.    0.04 -0.08  0.2 ]]
#7 Matrix A:
[[ 1.    0.    0.    0.44  0.12  0.2 ]
 [ 0.    1.    0.   -0.06  0.12  0.2 ]
 [ 0.    0.    1.    0.04 -0.08  0.2 ]]
Matrix a inverse:
[[ 0.44  0.12  0.2 ]
 [-0.06  0.12  0.2 ]
 [ 0.04 -0.08  0.2 ]]
Matrix A @ Matrix A invers

In [36]:
#1.4 จงตรวจสอบเมทริกซ์ผลลัพธ์ที่ได้จากข้อ 1.3 ว่าถูกต้องหรือไม่ หากถูกต้องแสดงข้อความว่า Correct หากไม่ถูกต้องแสดงข้อความ Incorrect โดยหากไม่ถูกต้องจงแก้ไขให้ถูกต้องด้วย
print(np.around(a@ainv,decimals=0))
if np.array_equal(np.around(a@ainv,decimals=0),np.identity(n)):
  print("Correct")
else:
  print("Incorrect")

[[ 1.  0.  0.]
 [-0.  1. -0.]
 [ 0. -0.  1.]]
Correct


In [54]:
#2
matrix_a =np.array([[1,2,1],[2,-4,5],[2,4,2]])

In [42]:
#2.1 จงหา det(A)
import numpy as np
print(matrix_a)
print('Det matrix_a = ', np.around(np.linalg.det(a) , decimals = 2))

[[1, 2, 1], [2, -4, 5], [2, 4, 2]]
Det matrix_a =  50.0


In [59]:
#2.2 จงหา Rank ของเมทริกซ์ที่กำหนดโดยใช้วิธีหาเมทริกซ์เอ็ซลอนลดรูปแบบแถว
# Rank =  numbers of non-zero rows or column and only zero matrix has rank zero.
print("manaul to find rank")
print('Rank matrix_a = ',np.linalg.matrix_rank(matrix_a))
print("___________________________________")
print("find rank with echelon rows operation")
import numpy as np
matrix_a =np.array([[1,2,1],[2,-4,5],[2,4,2]])
print('Matrix a:')
print(matrix_a)
n= matrix_a.shape[0]

def switch_rows(A,i,j):
  A[[i, j]] = A[[j, i]]
  return A

def scale_row(A,k,i):
  A[i] = k * A[i]
  return A

def add_row(A,k,i,j):
  A[i] += k * A[j]
  return A

a1 = scale_row(matrix_a,1/2,2) #R2/2
print('#1 Matrix a:')
print(a1)
a2 = add_row(a1,-1,2,0)
print("#2 Matrix a:")
print(a2)
a3 = add_row(a2,-2,1,0)
print("#3 Matrix a:")
print(a3)
a3_1 = scale_row(a3,(-1/8),1)
print("#3_1 Matrix a:")
print(a3_1)
a4 = add_row(a3_1,-2,0,1)
print("#4 Matrix a:")
print(a4)

result = np.all((a4 == 0), axis=1)
print('Is zero row?',result)
zero_row=len([i for i in range(n) if result[i] ])
rank_matrix_a= n-zero_row
print('1.1 Rank A =',rank_matrix_a)
print('1.2 Rank A = ',np.linalg.matrix_rank(a4))

manaul to find rank
Rank matrix_a =  2
___________________________________
find rank with echelon rows operation
Matrix a:
[[ 1  2  1]
 [ 2 -4  5]
 [ 2  4  2]]
#1 Matrix a:
[[ 1  2  1]
 [ 2 -4  5]
 [ 1  2  1]]
#2 Matrix a:
[[ 1  2  1]
 [ 2 -4  5]
 [ 0  0  0]]
#3 Matrix a:
[[ 1  2  1]
 [ 0 -8  3]
 [ 0  0  0]]
#3_1 Matrix a:
[[1 2 1]
 [0 1 0]
 [0 0 0]]
#4 Matrix a:
[[1 0 1]
 [0 1 0]
 [0 0 0]]
Is zero row? [False False  True]
1.1 Rank A = 2
1.2 Rank A =  2
