<a href="https://colab.research.google.com/github/chanyut12/mathforcom/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_21066_G2_w2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ให้นิสิต เลือกเมนู File-->Save a copy in drive เพื่อคัดลอกไฟล์ไปไว้ในไดร์ฟของนิสิตก่อน และเปลี่ยนชื่อไฟล์เป็น รหัสนิสิต_week2.ipynb ก่อนส่งงานค่ะ**

1.จงสร้างเมทริกซ์     
A =
\begin{bmatrix}
3 & 5  \\
-1 & 0
\end{bmatrix},
B =
\begin{bmatrix}
8 & 4  \\
2 & 1
\end{bmatrix}
และ

C =
\begin{bmatrix}
0 & 7  \\
1 & -5
\end{bmatrix}
โดยใช้ Python

1.1	จงหา det(A), det(B) และ det(C)

1.2 จงตรวจสอบว่าเมทริกซ์ B เป็นเมทริกซ์เอกฐาน หรือไม่ ถ้าเป็นแสดงข้อความ Singular matrix. ถ้าไม่เป็น จงหาผกผันของเมทริกซ์ B

1.3  จงตรวจสอบว่า det(3C) = det(3C)$^{T}$ หรือไม่
ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No

1.4 จงตรวจสอบว่า det(A) = det(A$^{-1}$) หรือไม่
ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No

1.5	จงตรวจสอบว่า det(AC) = det(A)*det(C) หรือไม่
ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No


2. จงสร้างเมทริกซ์   

A =
\begin{bmatrix}
1 & 4 & 1  \\
5 & -1 & 5  \\
0 & 3 & 0
\end{bmatrix}
และ

B =
\begin{bmatrix}
0 & 1 & 3  \\
0 & -2 & 5  \\
4 & -1 & 5
\end{bmatrix}

โดยใช้ Python

2.1 จงตรวจสอบว่า $det(A^{-1}) = \frac{1}{det(A^T)}$ หรือไม่  ถ้าเท่าให้แสดงข้อความ Yes ถ้าไม่เท่าแสดงข้อความ No

2.2 จงตรวจสอบว่า $(2B)^{-1} = 2^{-1}B^{-1}$ หรือไม่  ถ้าเท่าให้แสดงข้อความ Yes ถ้าไม่เท่าแสดงข้อความ No

2.3 จงหาค่า $M_{13}$ และ $C_{13}$ ของเมทริกซ์ A

2.4	จงหาเมทริกซ์ไมเนอร์ (Minor matrix: M(B)), เมทริกซ์โคแฟคเตอร์ (Cofactor matrix: Cof(B)) และเมทริกซ์ผูกพัน(Adjoint matrix: Adj(B))

2.5 จงหาค่าของ $Adj(BA)$ และ $Adj(A)Adj(B)$ แสดงผลออกทางหน้าจอ และตรวจสอบว่า $Adj(BA) = Adj(A)Adj(B)$ หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ถ้าไม่เท่าแสดงข้อความ No


In [ ]:
#ชื่อ......................................รหัส................

In [2]:
import numpy as np

In [33]:
#1.
A = [[3,5],[-1,0]]
B = [[8,4],[2,1]]
C = [[0,7],[1,-5]]


In [34]:
A = np.array(A)
B = np.array(B)
C = np.array(C)

In [12]:
#1.1 จงหา det(A), det(B) และ det(C)
print("det(A) = ",np.around(np.linalg.det(A),decimals=2))
print("det(B) = ",np.around(np.linalg.det(B),decimals=2))
print("det(C) = ",np.around(np.linalg.det(C),decimals=2))
# print(np.linalg.det(A)) -> 5.000000000000000000000000001

det(A) =  5.0
det(B) =  0.0
det(C) =  -7.0
5.000000000000001


In [23]:
#1.2 จงตรวจสอบว่าเมทริกซ์ B เป็นเมทริกซ์เอกฐาน หรือไม่ ถ้าเป็นแสดงข้อความ Singular matrix. ถ้าไม่เป็น จงหาผกผันของเมทริกซ์ B
if(np.linalg.det(B)==0):
  print("Singular matrix")
else:
  print(np.linalg.inv(B))


  #if det==0
# if np.isclose(np.linalg.det(B),0):
#   print("Singular matrix")
# else:
#   print(np.linalg.inv(B))

Singular matrix


In [10]:
#1.3 จงตรวจสอบว่า det(3C) = det(3C) T  หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No
if(np.linalg.det(3*C)==np.linalg.det(3*C).T):
  print("Yes")
else:
  print("No")

Yes


In [36]:
#1.4 จงตรวจสอบว่า det(A) = det(A −1 ) หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No
if(np.linalg.det(A)==np.linalg.det(np.linalg.inv(A))):
  print("Yes")
else:
  print("No")

No


In [38]:
#1.5 จงตรวจสอบว่า det(AC) = det(A)*det(C) หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ไม่เท่าแสดงข้อความ No
print(np.around(np.linalg.det(A@C),decimals=2))
print(np.around(np.linalg.det(A)*np.linalg.det(C),decimals=2))
if(np.around(np.linalg.det(A@C),decimals=2)==np.around(np.linalg.det(A)*np.linalg.det(C),decimals=2)):
  print("Yes")
else:
  print("No")

-35.0
-35.0
Yes


In [57]:
#2.
A = [[1,4,1],[5,-1,5],[0,3,0]]
B = [[0,1,3],[0,-2,5],[4,-1,5]]

A = np.array(A)
B = np.array(B)

In [27]:
#2.1 จงตรวจสอบว่า  det(A−1)=1det(AT)  หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ถ้าไม่เท่าแสดงข้อความ No
if(np.linalg.det(A) != 0):
  if(np.linalg.det(np.linalg.inv(A))==1/np.linalg.det(A).T):
    print("Yes")
  else:
    print("No")
else:
  print("This is singular matrix")

This is singular matrix


In [ ]:
#add


In [50]:
#2.2 จงตรวจสอบว่า  (2B)−1=2−1B−1  หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ถ้าไม่เท่าแสดงข้อความ No
# matrix2B = 2*B
# print(matrix2B)
inverse_of_matrix_2B = np.around(np.linalg.inv(matrix2B), decimals = 2)
print(inverse_of_matrix_2B)
matrixB_inverse = np.around((0.5)*np.linalg.inv(B), decimals=2)
print(matrixB_inverse)


if(np.array_equal(inverse_of_matrix_2B,matrixB_inverse)):
  print("Yes")
else:
  print("No")

[[ 0  2  6]
 [ 0 -4 10]
 [ 8 -2 10]]
[[-0.06 -0.09  0.12]
 [ 0.23 -0.14 -0.  ]
 [ 0.09  0.05  0.  ]]
[[-0.06 -0.09  0.12]
 [ 0.23 -0.14 -0.  ]
 [ 0.09  0.05  0.  ]]
Yes


In [30]:
#2.3 จงหาค่า M13 และ C13 ของเมทริกซ์ A
def minor_of_element(A,i,j):
    sub_A = np.delete(A,i-1,0)
    sub_A = np.delete(sub_A,j-1,1)
    M_ij = np.linalg.det(sub_A)
    return np.around(M_ij,decimals=2)


def cofactors_of_element(A,i,j):
  C_ij = pow(-1,i+j)*minor_of_element(A,i,j)
  return C_ij


print('Matrix A:')
print(A)
i = int(input('Enter row no. :'))
j = int(input('Enter column no. :'))
print('M(%d,%d) = ' %(i,j),minor_of_element(A,i,j))
print('C(%d,%d) = ' %(i,j),cofactors_of_element(A,i,j))


Matrix A:
[[ 1  4  1]
 [ 5 -1  5]
 [ 0  3  0]]
Enter row no. :1
Enter column no. :3
M(1,3) =  15.0
C(1,3) =  15.0


In [43]:
#2.4 จงหาเมทริกซ์ไมเนอร์ (Minor matrix: M(B)), เมทริกซ์โคแฟคเตอร์ (Cofactor matrix: Cof(B)) และเมทริกซ์ผูกพัน(Adjoint matrix: Adj(B))
B = [[0,1,3],[0,-2,5],[4,-1,5]]
B = np.array(B)
import numpy as np


def minor_of_element(A,i,j):
  sub_A = np.delete(A,i-1,0)
  sub_A = np.delete(sub_A,j-1,1)
  M_ij = np.linalg.det(sub_A)
  return np.around(M_ij,decimals=2)

def minor_matrix(A):
  m = A.shape[0]
  M_A = np.zeros([m,m])
  for i in range(1,m+1):
    for j in range(1,m+1):
      M_A[i-1,j-1] = minor_of_element(A,i,j)
  return M_A

def cofactor_matrix(A):
  m = np.shape(A)[0]
  C_A = np.zeros([m,m])
  for i in range(1,m+1):
    for j in range(1,m+1):
      C_A[i-1,j-1] = pow(-1,i+j)*minor_of_element(A,i,j)
  return C_A


def matrix_adj(matrix):
  return np.linalg.inv(matrix)*np.linalg.det(matrix)

print('Matrix B:')
print(B)
print('Minor Matrix of B:')
print(minor_matrix(A))
print('Cofactor Matrix of B:')
print(cofactor_matrix(A))
print("Adj matrix of B")
print(matrix_adj(B))
# print('Det A=',np.around(np.linalg.det(A),decimals=2))

# Summ = cofactor_matrix(A)*A[0]
# print('Det A=',Summ.sum())

Matrix B:
[[ 0  1  3]
 [ 0 -2  5]
 [ 4 -1  5]]
Minor Matrix of B:
[[-15.   0.  15.]
 [ -3.   0.   3.]
 [ 21.   0. -21.]]
Cofactor Matrix of B:
[[-15.  -0.  15.]
 [  3.   0.  -3.]
 [ 21.  -0. -21.]]
Adj matrix of B
[[ -5.  -8.  11.]
 [ 20. -12.  -0.]
 [  8.   4.   0.]]


In [58]:
#2.5 จงหาค่าของ  Adj(BA)  และ  Adj(A)Adj(B)  แสดงผลออกทางหน้าจอ และตรวจสอบว่า  Adj(BA)=Adj(A)Adj(B)  หรือไม่ ถ้าเท่าให้แสดงข้อความ Yes ถ้าไม่เท่าแสดงข้อความ No

def matrix_adj(matrix):
  return np.linalg.inv(matrix) * np.linalg.det(matrix)

adj_BA = matrix_adj(A@B)
adj_A =  matrix_adj(A)
adj_B =  matrix_adj(B)
print("Adj(BA) = ",adj_BA)
print("Adj(A)Adj(B) = ",adj_A@adj_B)


LinAlgError: Singular matrix