<a href="https://colab.research.google.com/github/chanyut12/mathforcom/blob/main/%E0%B8%AA%E0%B8%B3%E0%B9%80%E0%B8%99%E0%B8%B2%E0%B8%82%E0%B8%AD%E0%B8%87_66160295_G2_w4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ให้นิสิต เลือกเมนู File-->Save a copy in drive เพื่อคัดลอกไฟล์ไปไว้ในไดร์ฟของนิสิตก่อน และเปลี่ยนชื่อไฟล์เป็น รหัสนิสิต_week4.ipynb ก่อนส่งงานค่ะ**

1.จงตรวจสอบระบบสมการต่อไปนี้ว่าเป็นระบบสมการเอกพันธ์/ไม่เอกพันธ์ สอดคล้อง/ไม่สอดคล้อง หากเป็นระบบสมการสอดคล้อง มีผลเฉลยชุดเดียว/หลายชุด      


1.1

$2x_1+4x_2-5x_3 = 0 $

$4x_1-2x_2+x_3 = 0 $

$x_1+2x_2+3x_3 = 0 $


1.2

$3x_1-2x_2+x_3 +4x_4 = 5 $

$2x_1+x_2+4x_3-2x_4 = 9 $

$x_1-3x_2+x_3+6x_4 = 10 $

$-x_2+x_3+2x_4 = 8 $

1.3

$6x_1-2x_2+8x_3 +2x_4 = 0 $

$8x_1-4x_2+2x_3+4x_4 = 0 $

$x_1+x_2-x_3+5x_4 = 0 $

$4x_1-2x_2+x_3+2x_4 = 0 $



2. จงหาคำตอบของระบบสมการต่อไปนี้ โดยใช้เมทริกซ์ผกผัน (Inverse matrix)

$x_1+3x_2-x_3 +2x_4 = -1 $

$2x_1-x_2+3x_3-x_4 = 2 $

$x_1+2x_2+4x_3+x_4 = 3 $

$4x_2+x_3+5x_4 = 8 $

3. จงหาคำตอบของระบบสมการในข้อ 2. โดยการเรียกใช้งานฟังก์ชั่น np.linalg.solve และ เปรียบเทียบผลลัพธ์ที่ได้ในข้อ 2. กับผลลัพธ์ที่ได้ในข้อ 3. ว่าเท่ากันหรือไม่

4. จงหาคำตอบของระบบสมการในข้อ 2. โดยใช้ Cramer’s rule

5. จงหาคำตอบของระบบสมการในข้อ 2. โดยใช้ Gaussian Elimination



In [ ]:
#ชื่อ ชาญยุทธ ลิสวัสดิ์ รหัส 66160295

In [ ]:
#1.จงตรวจสอบระบบสมการต่อไปนี้ว่าเป็นระบบสมการเอกพันธ์/ไม่เอกพันธ์ สอดคล้อง/ไม่สอดคล้อง
# หากเป็นระบบสมการสอดคล้อง มีผลเฉลยชุดเดียว/หลายชุด
#1.1
import numpy as np
A = np.array([[2,4,-5],[4,-2,-1],[1,2,3]],float)
B = np.array([[0],[0],[0]])

print("1.1")
print('Matrix A:')
print(A)
n = A.shape[1]
AB = np.hstack([A,B])
print('Matrix [A:B]:')
print(AB)

detA = np.linalg.det(A)
print('detA =',round(detA))
rankA=np.linalg.matrix_rank(A)
print('rank A =',rankA)
rankAB=np.linalg.matrix_rank(AB)
print('rank [A:B] =',rankAB)
print('Number of variables =',n)
if np.array_equal(B, np.zeros(B.shape)):
  print('This is a homogeneous system of linear equations.')
  if round(detA)!=0:
    print('The equations are consistent and have unique solution.')
    for i in range(n):
      print('x', i + 1, ' = 0')
  else:
    print('The equations are consistent and have multiple solutions.')
else:
  print('This is a non-homogeneous system of linear equations.')
  if rankA==rankAB and rankA==n :
    print('The equations are consistent and have unique solution.')
  elif rankA==rankAB and rankA<n :
    print('The equations are consistent and have multiple solutions.')
  else:
    print('The equations are inconsistent and has no solution.')

1.1
Matrix A:
[[ 2.  4. -5.]
 [ 4. -2. -1.]
 [ 1.  2.  3.]]
Matrix [A:B]:
[[ 2.  4. -5.  0.]
 [ 4. -2. -1.  0.]
 [ 1.  2.  3.  0.]]
detA = -110
rank A = 3
rank [A:B] = 3
Number of variables = 3
This is a homogeneous system of linear equations.
The equations are consistent and have unique solution.
x 1  = 0
x 2  = 0
x 3  = 0


In [ ]:
#1.2
import numpy as np
A = np.array([[3, -2, 1, 4],[2, 1, 4, -2],[1, -3, 1, 6],[0, -1, 1, 2]],float)
B = np.array([[5],[9],[10], [8]])

print("1.2")
print('Matrix A:')
print(A)
n = A.shape[1]
AB = np.hstack([A,B])
print('Matrix [A:B]:')
print(AB)

detA = np.linalg.det(A)
print('detA =',round(detA))
rankA=np.linalg.matrix_rank(A)
print('rank A =',rankA)
rankAB=np.linalg.matrix_rank(AB)
print('rank [A:B] =',rankAB)
print('Number of variables =',n)
if np.array_equal(B, np.zeros(B.shape)):
  print('This is a homogeneous system of linear equations.')
  if round(detA)!=0:
    print('The equations are consistent and have unique solution.')
    for i in range(n):
      print('x', i + 1, ' = 0')
  else:
    print('The equations are consistent and have multiple solutions.')
else:
  print('This is a non-homogeneous system of linear equations.')
  if rankA==rankAB and rankA==n :
    print('The equations are consistent and have unique solution.')
  elif rankA==rankAB and rankA<n :
    print('The equations are consistent and have multiple solutions.')
  else:
    print('The equations are inconsistent and has no solution.')

1.2
Matrix A:
[[ 3. -2.  1.  4.]
 [ 2.  1.  4. -2.]
 [ 1. -3.  1.  6.]
 [ 0. -1.  1.  2.]]
Matrix [A:B]:
[[ 3. -2.  1.  4.  5.]
 [ 2.  1.  4. -2.  9.]
 [ 1. -3.  1.  6. 10.]
 [ 0. -1.  1.  2.  8.]]
detA = 0
rank A = 3
rank [A:B] = 4
Number of variables = 4
This is a non-homogeneous system of linear equations.
The equations are inconsistent and has no solution.


In [ ]:
#1.3
A = np.array([[6, -2, 8, 2],[8, -4, 2, 4],[1, 1, -1, 5],[4, -2, 1, 2]],float)
B = np.array([[0],[0],[0], [0]])

print("1.3")
print('Matrix A:')
print(A)
n = A.shape[1]
AB = np.hstack([A,B])
print('Matrix [A:B]:')
print(AB)

detA = np.linalg.det(A)
print('detA =',round(detA))
rankA=np.linalg.matrix_rank(A)
print('rank A =',rankA)
rankAB=np.linalg.matrix_rank(AB)
print('rank [A:B] =',rankAB)
print('Number of variables =',n)
if np.array_equal(B, np.zeros(B.shape)):
  print('This is a homogeneous system of linear equations.')
  if round(detA)!=0:
    print('The equations are consistent and have unique solution.')
    for i in range(n):
      print('x', i + 1, ' = 0')
  else:
    print('The equations are consistent and have multiple solutions.')
else:
  print('This is a non-homogeneous system of linear equations.')
  if rankA==rankAB and rankA==n :
    print('The equations are consistent and have unique solution.')
  elif rankA==rankAB and rankA<n :
    print('The equations are consistent and have multiple solutions.')
  else:
    print('The equations are inconsistent and has no solution.')

1.3
Matrix A:
[[ 6. -2.  8.  2.]
 [ 8. -4.  2.  4.]
 [ 1.  1. -1.  5.]
 [ 4. -2.  1.  2.]]
Matrix [A:B]:
[[ 6. -2.  8.  2.  0.]
 [ 8. -4.  2.  4.  0.]
 [ 1.  1. -1.  5.  0.]
 [ 4. -2.  1.  2.  0.]]
detA = 0
rank A = 3
rank [A:B] = 3
Number of variables = 4
This is a homogeneous system of linear equations.
The equations are consistent and have multiple solutions.


In [ ]:
#2.จงหาคำตอบของระบบสมการต่อไปนี้ โดยใช้เมทริกซ์ผกผัน (Inverse matrix)
import numpy as np
A = np.array([[1, 3, -1, 2],[2, -1, 3, -1],[1, 2, 4, 1],[0, 4, 1, 5]],float)
B = np.array([[-1, 2, 3, 8]])
BT = B.transpose()
print("2.")
print('Matrix A:')
print(A)
print('Matrix B:')
print(BT)
inverseA = np.linalg.inv(A)
print('Inverse Matrix of A:')
print(inverseA)
solutionX = np.around(inverseA@BT, decimals=2)
n = solutionX.shape[0]
print('Solution Matrix of A:')
print(solutionX)
for i in range(n):
  print('x',i+1,' = ',solutionX[i])

2.
Matrix A:
[[ 1.  3. -1.  2.]
 [ 2. -1.  3. -1.]
 [ 1.  2.  4.  1.]
 [ 0.  4.  1.  5.]]
Matrix B:
[[-1]
 [ 2]
 [ 3]
 [ 8]]
Inverse Matrix of A:
[[ 0.31944444  0.48611111 -0.29166667  0.02777778]
 [ 0.30555556 -0.36111111  0.41666667 -0.27777778]
 [-0.18055556 -0.01388889  0.20833333  0.02777778]
 [-0.20833333  0.29166667 -0.375       0.41666667]]
Solution Matrix of A:
[[-0.]
 [-2.]
 [ 1.]
 [ 3.]]
x 1  =  [-0.]
x 2  =  [-2.]
x 3  =  [1.]
x 4  =  [3.]


In [ ]:
#3.จงหาคำตอบของระบบสมการในข้อ 2.
# โดยการเรียกใช้งานฟังก์ชั่น np.linalg.solve และ เปรียบเทียบผลลัพธ์ที่ได้ในข้อ 2. กับผลลัพธ์ที่ได้ในข้อ 3. ว่าเท่ากันหรือไม่
print("3.")
print('Matrix A:')
print(A)
n = A.shape[1]
print('Matrix B:')
print(BT)

x = np.linalg.solve(A, BT)
print('\nSolution is: ')
print(x)
for i in range(n):
  print('x%d = %0.2f' %(i,x[i]), end = '\t')

3.
Matrix A:
[[ 1.  3. -1.  2.]
 [ 2. -1.  3. -1.]
 [ 1.  2.  4.  1.]
 [ 0.  4.  1.  5.]]
Matrix B:
[[-1]
 [ 2]
 [ 3]
 [ 8]]

Solution is: 
[[-2.22044605e-16]
 [-2.00000000e+00]
 [ 1.00000000e+00]
 [ 3.00000000e+00]]
x0 = -0.00	x1 = -2.00	x2 = 1.00	x3 = 3.00	

<ipython-input-14-6e54abfe173c>:14: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print('x%d = %0.2f' %(i,x[i]), end = '\t')


In [ ]:
#4.จงหาคำตอบของระบบสมการในข้อ 2. โดยใช้ Cramer’s rule
A = np.array([[1, 3, -1, 2],[2, -1, 3, -1],[1, 2, 4, 1],[0, 4, 1, 5]],float)
B = np.array([[-1, 2, 3, 8]])
print("4.")
print('Matrix A:')
print(A)
print('Matrix B:')
print(B)
detA = np.around(np.linalg.det(A),decimals=2)
print('det A =',detA)

def Cramer(A,B,i):
  MAcopy = A[:,i].copy()
  A[:,i] = B
  print("Matrix A with a column of B")
  print(A)
  x = np.linalg.det(A)
  A[:,i] = MAcopy.copy()
  return x
if detA==0:
  sys.exit("No solutions, det(A) is zero.")
else:
  for i in range(A.shape[1]):
    solutionX = np.around(Cramer(A,B,i)/detA,decimals=2)
    print('X',i+1,'= ',solutionX)

4.
Matrix A:
[[ 1.  3. -1.  2.]
 [ 2. -1.  3. -1.]
 [ 1.  2.  4.  1.]
 [ 0.  4.  1.  5.]]
Matrix B:
[[-1  2  3  8]]
det A = -72.0
Matrix A with a column of B
[[-1.  3. -1.  2.]
 [ 2. -1.  3. -1.]
 [ 3.  2.  4.  1.]
 [ 8.  4.  1.  5.]]
X 1 =  -0.0
Matrix A with a column of B
[[ 1. -1. -1.  2.]
 [ 2.  2.  3. -1.]
 [ 1.  3.  4.  1.]
 [ 0.  8.  1.  5.]]
X 2 =  -2.0
Matrix A with a column of B
[[ 1.  3. -1.  2.]
 [ 2. -1.  2. -1.]
 [ 1.  2.  3.  1.]
 [ 0.  4.  8.  5.]]
X 3 =  1.0
Matrix A with a column of B
[[ 1.  3. -1. -1.]
 [ 2. -1.  3.  2.]
 [ 1.  2.  4.  3.]
 [ 0.  4.  1.  8.]]
X 4 =  3.0


In [ ]:
#5.จงหาคำตอบของระบบสมการในข้อ 2. โดยใช้ Gaussian Elimination
import numpy as np
A = np.array([[1, 3, -1, 2],[2, -1, 3, -1],[1, 2, 4, 1],[0, 4, 1, 5]],float)
B = np.array([[-1],[2],[3],[8]])
print('5.')
print('Matrix A:')
print(A)
n=A.shape[1]
AB = np.hstack([A,B])
print('Matrix [A:B]:')
print(AB)

def switch_rows(A,i,j):
  A[[i, j]] = A[[j, i]]
  return A

def scale_row(A,k,i):
  A[i] = k * A[i]
  return A

def add_row(A,k,i,j):
  A[i] += k * A[j]
  return A

5.
Matrix A:
[[ 1.  3. -1.  2.]
 [ 2. -1.  3. -1.]
 [ 1.  2.  4.  1.]
 [ 0.  4.  1.  5.]]
Matrix [A:B]:
[[ 1.  3. -1.  2. -1.]
 [ 2. -1.  3. -1.  2.]
 [ 1.  2.  4.  1.  3.]
 [ 0.  4.  1.  5.  8.]]


In [ ]:
#เปลี่ยน a12(2), a13(1) = 0 โดย R2->R2-2R1 ; R3->R3-1R1
A1 = add_row(AB,-2,1,0)
A1 = add_row(A1,-1,2,0)
print('#1 Matrix [A:B]:')
print(A1)

#1 Matrix [A:B]:
[[ 1.  3. -1.  2. -1.]
 [ 0. -7.  5. -5.  4.]
 [ 0. -1.  5. -1.  4.]
 [ 0.  4.  1.  5.  8.]]


In [ ]:
#สลับแถว R2 <-> R3
A2 = switch_rows(A1,1,2)
print('#2 Matrix [A:B]:')
print(A2)

#2 Matrix [A:B]:
[[ 1.  3. -1.  2. -1.]
 [ 0. -1.  5. -1.  4.]
 [ 0. -7.  5. -5.  4.]
 [ 0.  4.  1.  5.  8.]]


In [ ]:
#เปลี่ยน a12(-1) = 1 โดย R2-> -1R2
A3 = scale_row(A2,-1,1)
print('#3 Matrix [A:B]:')
print(A3)

#3 Matrix [A:B]:
[[ 1.  3. -1.  2. -1.]
 [-0.  1. -5.  1. -4.]
 [ 0. -7.  5. -5.  4.]
 [ 0.  4.  1.  5.  8.]]


In [ ]:
#เปลี่ยน a32(-7), a42(4) = 0 โดย R3-> R3+7R2 / R4-> R4-4R2
A4 = add_row(A3,7,2,1)
A4 = add_row(A4,-4,3,1)
print('#4 Matrix [A:B]:')
print(A4)

#4 Matrix [A:B]:
[[  1.   3.  -1.   2.  -1.]
 [ -0.   1.  -5.   1.  -4.]
 [  0.   0. -30.   2. -24.]
 [  0.   0.  21.   1.  24.]]


In [ ]:
#เปลี่ยน a33(-30) = 1 โดย R3-> -1/30R3
A5 = scale_row(A4,1/-30,2)
print('#5 Matrix [A:B]:')
print(A5)

#5 Matrix [A:B]:
[[ 1.          3.         -1.          2.         -1.        ]
 [-0.          1.         -5.          1.         -4.        ]
 [-0.         -0.          1.         -0.06666667  0.8       ]
 [ 0.          0.         21.          1.         24.        ]]


In [ ]:
#เปลี่ยน a43(21) = 0 โดย R4=> R4-21R3
A6 = add_row(A5,-21,3,2)
print('#6 Matrix [A:B]:')
print(A6)

#6 Matrix [A:B]:
[[ 1.          3.         -1.          2.         -1.        ]
 [-0.          1.         -5.          1.         -4.        ]
 [-0.         -0.          1.         -0.06666667  0.8       ]
 [ 0.          0.          0.          2.4         7.2       ]]


In [ ]:
#เปลี่ยน a44(2.4) = 1 โดย R4=> 1/4R4
A7 = scale_row(A4,1/2.4,3)
print('#7 Matrix [A:B]:')
print(A7)

#7 Matrix [A:B]:
[[ 1.          3.         -1.          2.         -1.        ]
 [-0.          1.         -5.          1.         -4.        ]
 [-0.         -0.          1.         -0.06666667  0.8       ]
 [ 0.          0.          0.          1.          3.        ]]


In [ ]:
a = A7
n = A.shape[1]
x = np.zeros(n)

x[n-1] = a[n-1][n]/a[n-1][n-1]
for i in range(n-2,-1,-1):
  x[i] = a[i][n]
  for j in range(i+1,n):
    x[i] = x[i] - a[i][j]*x[j]
  x[i] = x[i]/a[i][i]

print('Solution is: ')
for i in range(n):
  print('x%d = %0.2f' %(i,x[i]), end = '\t')

Solution is: 
x0 = 0.00	x1 = -2.00	x2 = 1.00	x3 = 3.00	